/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccueilRouteImport } from './routes/accueil'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AccueilIndexRouteImport } from './routes/accueil.index'
import { Route as AccueilAbonnementRouteImport } from './routes/accueil.abonnement'
import { Route as AccueilCommunauteRouteImport } from './routes/accueil.communaute'
import { Route as AccueilDecouvrirRouteImport } from './routes/accueil.decouvrir'
import { Route as AccueilDemandesRouteImport } from './routes/accueil.demandes'
import { Route as AccueilMessagesRouteImport } from './routes/accueil.messages'
import { Route as AccueilProfilRouteImport } from './routes/accueil.profil'
import { Route as AccueilParametresBloquesRouteImport } from './routes/accueil.parametres.bloques'
import { Route as AccueilParametresLangueRouteImport } from './routes/accueil.parametres.langue'
import { Route as AccueilParametresNotificationsRouteImport } from './routes/accueil.parametres.notifications'
import { Route as AccueilParametresSecuriteRouteImport } from './routes/accueil.parametres.securite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilRoute = AccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilIndexRoute = AccueilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccueilRoute,
} as any)
const AccueilAbonnementRoute = AccueilAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => AccueilRoute,
} as any)
const AccueilCommunauteRoute = AccueilCommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => AccueilRoute,
} as any)
const AccueilDecouvrirRoute = AccueilDecouvrirRouteImport.update({
  id: '/decouvrir',
  path: '/decouvrir',
  getParentRoute: () => AccueilRoute,
} as any)
const AccueilDemandesRoute = AccueilDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AccueilRoute,
} as any)
const AccueilMessagesRoute = AccueilMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AccueilRoute,
} as any)
const AccueilProfilRoute = AccueilProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AccueilRoute,
} as any)
const AccueilParametresBloquesRoute =
  AccueilParametresBloquesRouteImport.update({
    id: '/parametres/bloques',
    path: '/parametres/bloques',
    getParentRoute: () => AccueilRoute,
  } as any)
const AccueilParametresLangueRoute = AccueilParametresLangueRouteImport.update({
  id: '/parametres/langue',
  path: '/parametres/langue',
  getParentRoute: () => AccueilRoute,
} as any)
const AccueilParametresNotificationsRoute =
  AccueilParametresNotificationsRouteImport.update({
    id: '/parametres/notifications',
    path: '/parametres/notifications',
    getParentRoute: () => AccueilRoute,
  } as any)
const AccueilParametresSecuriteRoute =
  AccueilParametresSecuriteRouteImport.update({
    id: '/parametres/securite',
    path: '/parametres/securite',
    getParentRoute: () => AccueilRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRouteWithChildren
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/accueil/abonnement': typeof AccueilAbonnementRoute
  '/accueil/communaute': typeof AccueilCommunauteRoute
  '/accueil/decouvrir': typeof AccueilDecouvrirRoute
  '/accueil/demandes': typeof AccueilDemandesRoute
  '/accueil/messages': typeof AccueilMessagesRoute
  '/accueil/profil': typeof AccueilProfilRoute
  '/accueil/': typeof AccueilIndexRoute
  '/accueil/parametres/bloques': typeof AccueilParametresBloquesRoute
  '/accueil/parametres/langue': typeof AccueilParametresLangueRoute
  '/accueil/parametres/notifications': typeof AccueilParametresNotificationsRoute
  '/accueil/parametres/securite': typeof AccueilParametresSecuriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/accueil/abonnement': typeof AccueilAbonnementRoute
  '/accueil/communaute': typeof AccueilCommunauteRoute
  '/accueil/decouvrir': typeof AccueilDecouvrirRoute
  '/accueil/demandes': typeof AccueilDemandesRoute
  '/accueil/messages': typeof AccueilMessagesRoute
  '/accueil/profil': typeof AccueilProfilRoute
  '/accueil': typeof AccueilIndexRoute
  '/accueil/parametres/bloques': typeof AccueilParametresBloquesRoute
  '/accueil/parametres/langue': typeof AccueilParametresLangueRoute
  '/accueil/parametres/notifications': typeof AccueilParametresNotificationsRoute
  '/accueil/parametres/securite': typeof AccueilParametresSecuriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRouteWithChildren
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/accueil/abonnement': typeof AccueilAbonnementRoute
  '/accueil/communaute': typeof AccueilCommunauteRoute
  '/accueil/decouvrir': typeof AccueilDecouvrirRoute
  '/accueil/demandes': typeof AccueilDemandesRoute
  '/accueil/messages': typeof AccueilMessagesRoute
  '/accueil/profil': typeof AccueilProfilRoute
  '/accueil/': typeof AccueilIndexRoute
  '/accueil/parametres/bloques': typeof AccueilParametresBloquesRoute
  '/accueil/parametres/langue': typeof AccueilParametresLangueRoute
  '/accueil/parametres/notifications': typeof AccueilParametresNotificationsRoute
  '/accueil/parametres/securite': typeof AccueilParametresSecuriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accueil'
    | '/inscription'
    | '/login'
    | '/onboarding'
    | '/accueil/abonnement'
    | '/accueil/communaute'
    | '/accueil/decouvrir'
    | '/accueil/demandes'
    | '/accueil/messages'
    | '/accueil/profil'
    | '/accueil/'
    | '/accueil/parametres/bloques'
    | '/accueil/parametres/langue'
    | '/accueil/parametres/notifications'
    | '/accueil/parametres/securite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inscription'
    | '/login'
    | '/onboarding'
    | '/accueil/abonnement'
    | '/accueil/communaute'
    | '/accueil/decouvrir'
    | '/accueil/demandes'
    | '/accueil/messages'
    | '/accueil/profil'
    | '/accueil'
    | '/accueil/parametres/bloques'
    | '/accueil/parametres/langue'
    | '/accueil/parametres/notifications'
    | '/accueil/parametres/securite'
  id:
    | '__root__'
    | '/'
    | '/accueil'
    | '/inscription'
    | '/login'
    | '/onboarding'
    | '/accueil/abonnement'
    | '/accueil/communaute'
    | '/accueil/decouvrir'
    | '/accueil/demandes'
    | '/accueil/messages'
    | '/accueil/profil'
    | '/accueil/'
    | '/accueil/parametres/bloques'
    | '/accueil/parametres/langue'
    | '/accueil/parametres/notifications'
    | '/accueil/parametres/securite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccueilRoute: typeof AccueilRouteWithChildren
  InscriptionRoute: typeof InscriptionRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil': {
      id: '/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil/': {
      id: '/accueil/'
      path: '/'
      fullPath: '/accueil/'
      preLoaderRoute: typeof AccueilIndexRouteImport
      parentRoute: typeof AccueilRoute
    }
    '/accueil/abonnement': {
      id: '/accueil/abonnement'
      path: '/abonnement'
      fullPath: '/accueil/abonnement'
      preLoaderRoute: typeof AccueilAbonnementRouteImport
      parentRoute: typeof AccueilRoute
    }
    '/accueil/communaute': {
      id: '/accueil/communaute'
      path: '/communaute'
      fullPath: '/accueil/communaute'
      preLoaderRoute: typeof AccueilCommunauteRouteImport
      parentRoute: typeof AccueilRoute
    }
    '/accueil/decouvrir': {
      id: '/accueil/decouvrir'
      path: '/decouvrir'
      fullPath: '/accueil/decouvrir'
      preLoaderRoute: typeof AccueilDecouvrirRouteImport
      parentRoute: typeof AccueilRoute
    }
    '/accueil/demandes': {
      id: '/accueil/demandes'
      path: '/demandes'
      fullPath: '/accueil/demandes'
      preLoaderRoute: typeof AccueilDemandesRouteImport
      parentRoute: typeof AccueilRoute
    }
    '/accueil/messages': {
      id: '/accueil/messages'
      path: '/messages'
      fullPath: '/accueil/messages'
      preLoaderRoute: typeof AccueilMessagesRouteImport
      parentRoute: typeof AccueilRoute
    }
    '/accueil/profil': {
      id: '/accueil/profil'
      path: '/profil'
      fullPath: '/accueil/profil'
      preLoaderRoute: typeof AccueilProfilRouteImport
      parentRoute: typeof AccueilRoute
    }
    '/accueil/parametres/bloques': {
      id: '/accueil/parametres/bloques'
      path: '/parametres/bloques'
      fullPath: '/accueil/parametres/bloques'
      preLoaderRoute: typeof AccueilParametresBloquesRouteImport
      parentRoute: typeof AccueilRoute
    }
    '/accueil/parametres/langue': {
      id: '/accueil/parametres/langue'
      path: '/parametres/langue'
      fullPath: '/accueil/parametres/langue'
      preLoaderRoute: typeof AccueilParametresLangueRouteImport
      parentRoute: typeof AccueilRoute
    }
    '/accueil/parametres/notifications': {
      id: '/accueil/parametres/notifications'
      path: '/parametres/notifications'
      fullPath: '/accueil/parametres/notifications'
      preLoaderRoute: typeof AccueilParametresNotificationsRouteImport
      parentRoute: typeof AccueilRoute
    }
    '/accueil/parametres/securite': {
      id: '/accueil/parametres/securite'
      path: '/parametres/securite'
      fullPath: '/accueil/parametres/securite'
      preLoaderRoute: typeof AccueilParametresSecuriteRouteImport
      parentRoute: typeof AccueilRoute
    }
  }
}

interface AccueilRouteChildren {
  AccueilAbonnementRoute: typeof AccueilAbonnementRoute
  AccueilCommunauteRoute: typeof AccueilCommunauteRoute
  AccueilDecouvrirRoute: typeof AccueilDecouvrirRoute
  AccueilDemandesRoute: typeof AccueilDemandesRoute
  AccueilMessagesRoute: typeof AccueilMessagesRoute
  AccueilProfilRoute: typeof AccueilProfilRoute
  AccueilIndexRoute: typeof AccueilIndexRoute
  AccueilParametresBloquesRoute: typeof AccueilParametresBloquesRoute
  AccueilParametresLangueRoute: typeof AccueilParametresLangueRoute
  AccueilParametresNotificationsRoute: typeof AccueilParametresNotificationsRoute
  AccueilParametresSecuriteRoute: typeof AccueilParametresSecuriteRoute
}

const AccueilRouteChildren: AccueilRouteChildren = {
  AccueilAbonnementRoute: AccueilAbonnementRoute,
  AccueilCommunauteRoute: AccueilCommunauteRoute,
  AccueilDecouvrirRoute: AccueilDecouvrirRoute,
  AccueilDemandesRoute: AccueilDemandesRoute,
  AccueilMessagesRoute: AccueilMessagesRoute,
  AccueilProfilRoute: AccueilProfilRoute,
  AccueilIndexRoute: AccueilIndexRoute,
  AccueilParametresBloquesRoute: AccueilParametresBloquesRoute,
  AccueilParametresLangueRoute: AccueilParametresLangueRoute,
  AccueilParametresNotificationsRoute: AccueilParametresNotificationsRoute,
  AccueilParametresSecuriteRoute: AccueilParametresSecuriteRoute,
}

const AccueilRouteWithChildren =
  AccueilRoute._addFileChildren(AccueilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccueilRoute: AccueilRouteWithChildren,
  InscriptionRoute: InscriptionRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
