/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppAbonnementRouteImport } from './routes/_app.abonnement'
import { Route as AppAccueilRouteImport } from './routes/_app.accueil'
import { Route as AppCommunauteRouteImport } from './routes/_app.communaute'
import { Route as AppDecouvrirRouteImport } from './routes/_app.decouvrir'
import { Route as AppDemandesRouteImport } from './routes/_app.demandes'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppProfilRouteImport } from './routes/_app.profil'
import { Route as AppParametresBloquesRouteImport } from './routes/_app.parametres.bloques'
import { Route as AppParametresLangueRouteImport } from './routes/_app.parametres.langue'
import { Route as AppParametresNotificationsRouteImport } from './routes/_app.parametres.notifications'
import { Route as AppParametresSecuriteRouteImport } from './routes/_app.parametres.securite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAbonnementRoute = AppAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => AppRoute,
} as any)
const AppAccueilRoute = AppAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunauteRoute = AppCommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => AppRoute,
} as any)
const AppDecouvrirRoute = AppDecouvrirRouteImport.update({
  id: '/decouvrir',
  path: '/decouvrir',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandesRoute = AppDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresBloquesRoute = AppParametresBloquesRouteImport.update({
  id: '/parametres/bloques',
  path: '/parametres/bloques',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresLangueRoute = AppParametresLangueRouteImport.update({
  id: '/parametres/langue',
  path: '/parametres/langue',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresNotificationsRoute =
  AppParametresNotificationsRouteImport.update({
    id: '/parametres/notifications',
    path: '/parametres/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppParametresSecuriteRoute = AppParametresSecuriteRouteImport.update({
  id: '/parametres/securite',
  path: '/parametres/securite',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/abonnement': typeof AppAbonnementRoute
  '/accueil': typeof AppAccueilRoute
  '/communaute': typeof AppCommunauteRoute
  '/decouvrir': typeof AppDecouvrirRoute
  '/demandes': typeof AppDemandesRoute
  '/messages': typeof AppMessagesRoute
  '/profil': typeof AppProfilRoute
  '/parametres/bloques': typeof AppParametresBloquesRoute
  '/parametres/langue': typeof AppParametresLangueRoute
  '/parametres/notifications': typeof AppParametresNotificationsRoute
  '/parametres/securite': typeof AppParametresSecuriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/abonnement': typeof AppAbonnementRoute
  '/accueil': typeof AppAccueilRoute
  '/communaute': typeof AppCommunauteRoute
  '/decouvrir': typeof AppDecouvrirRoute
  '/demandes': typeof AppDemandesRoute
  '/messages': typeof AppMessagesRoute
  '/profil': typeof AppProfilRoute
  '/parametres/bloques': typeof AppParametresBloquesRoute
  '/parametres/langue': typeof AppParametresLangueRoute
  '/parametres/notifications': typeof AppParametresNotificationsRoute
  '/parametres/securite': typeof AppParametresSecuriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/abonnement': typeof AppAbonnementRoute
  '/_app/accueil': typeof AppAccueilRoute
  '/_app/communaute': typeof AppCommunauteRoute
  '/_app/decouvrir': typeof AppDecouvrirRoute
  '/_app/demandes': typeof AppDemandesRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/parametres/bloques': typeof AppParametresBloquesRoute
  '/_app/parametres/langue': typeof AppParametresLangueRoute
  '/_app/parametres/notifications': typeof AppParametresNotificationsRoute
  '/_app/parametres/securite': typeof AppParametresSecuriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inscription'
    | '/login'
    | '/onboarding'
    | '/abonnement'
    | '/accueil'
    | '/communaute'
    | '/decouvrir'
    | '/demandes'
    | '/messages'
    | '/profil'
    | '/parametres/bloques'
    | '/parametres/langue'
    | '/parametres/notifications'
    | '/parametres/securite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inscription'
    | '/login'
    | '/onboarding'
    | '/abonnement'
    | '/accueil'
    | '/communaute'
    | '/decouvrir'
    | '/demandes'
    | '/messages'
    | '/profil'
    | '/parametres/bloques'
    | '/parametres/langue'
    | '/parametres/notifications'
    | '/parametres/securite'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/inscription'
    | '/login'
    | '/onboarding'
    | '/_app/abonnement'
    | '/_app/accueil'
    | '/_app/communaute'
    | '/_app/decouvrir'
    | '/_app/demandes'
    | '/_app/messages'
    | '/_app/profil'
    | '/_app/parametres/bloques'
    | '/_app/parametres/langue'
    | '/_app/parametres/notifications'
    | '/_app/parametres/securite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InscriptionRoute: typeof InscriptionRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/abonnement': {
      id: '/_app/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AppAbonnementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accueil': {
      id: '/_app/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AppAccueilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communaute': {
      id: '/_app/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof AppCommunauteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decouvrir': {
      id: '/_app/decouvrir'
      path: '/decouvrir'
      fullPath: '/decouvrir'
      preLoaderRoute: typeof AppDecouvrirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demandes': {
      id: '/_app/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof AppDemandesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres/bloques': {
      id: '/_app/parametres/bloques'
      path: '/parametres/bloques'
      fullPath: '/parametres/bloques'
      preLoaderRoute: typeof AppParametresBloquesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres/langue': {
      id: '/_app/parametres/langue'
      path: '/parametres/langue'
      fullPath: '/parametres/langue'
      preLoaderRoute: typeof AppParametresLangueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres/notifications': {
      id: '/_app/parametres/notifications'
      path: '/parametres/notifications'
      fullPath: '/parametres/notifications'
      preLoaderRoute: typeof AppParametresNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres/securite': {
      id: '/_app/parametres/securite'
      path: '/parametres/securite'
      fullPath: '/parametres/securite'
      preLoaderRoute: typeof AppParametresSecuriteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAbonnementRoute: typeof AppAbonnementRoute
  AppAccueilRoute: typeof AppAccueilRoute
  AppCommunauteRoute: typeof AppCommunauteRoute
  AppDecouvrirRoute: typeof AppDecouvrirRoute
  AppDemandesRoute: typeof AppDemandesRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppProfilRoute: typeof AppProfilRoute
  AppParametresBloquesRoute: typeof AppParametresBloquesRoute
  AppParametresLangueRoute: typeof AppParametresLangueRoute
  AppParametresNotificationsRoute: typeof AppParametresNotificationsRoute
  AppParametresSecuriteRoute: typeof AppParametresSecuriteRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAbonnementRoute: AppAbonnementRoute,
  AppAccueilRoute: AppAccueilRoute,
  AppCommunauteRoute: AppCommunauteRoute,
  AppDecouvrirRoute: AppDecouvrirRoute,
  AppDemandesRoute: AppDemandesRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppProfilRoute: AppProfilRoute,
  AppParametresBloquesRoute: AppParametresBloquesRoute,
  AppParametresLangueRoute: AppParametresLangueRoute,
  AppParametresNotificationsRoute: AppParametresNotificationsRoute,
  AppParametresSecuriteRoute: AppParametresSecuriteRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InscriptionRoute: InscriptionRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
